modLoader = "javafml"
license = "ARR"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/nyctography/issues"

[[mods]]
modId = "nyctography"
version = "26.1.2.0"
displayName = "Nyctography"
updateJSONURL = "https://updates.blamejared.com/get?n=nyctography&gv=26.1.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/nyctography"
logoFile = "logo_nyctography.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Adds a Nyctography font set to Minecraft."

[[mixins]]
config = "nyctography.common.mixins.json"

[[mixins]]
config = "nyctography.neoforge.mixins.json"

[[dependencies.nyctography]]
modId = "minecraft"
type = "required"
versionRange = "26.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.nyctography]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

